### ISSUE TITLE
calendar 디자인 관련 이슈

### ISSUE THREAD

**Issue by yestw** [group-for-study/todo_list#8]
![image](https://github.com/group-for-study/todo_list/assets/103083087/c87b6398-5290-4617-97a7-ea1cb9c135f6)

이런 디자인 괜찮으신가요?
리액트 캘린더 라이브러리 사용한 상태이고, 디자인을 기존 것 에서 커스텀을 조금 했습니다.
현재까지는 메인페이지에서 조회 해온 데이터들 중 created를 비교해서 투두가 작성되어 있는 날짜는 메모 이모지를 통해 표현했습니다.

만약 이대로 간다면 필요한 api 는
1. 해당되는 날짜를 눌렀을 때 조회하는 api
2. 동일 날짜에 중복으로 투두 작성이 가능한지
3. 조회 자체가 달별로 되도록 수정
4. 작성을 날짜를 클릭해서 하는지, 작성 버튼을 누르면 본인이 날짜를 선택할 수 있도록 하는지
등등이 있는 것 같습니다.

프론트에서 앞으로 해야 할 작업은
1. 메인에 있는 input, 투두리스트 데이터들을 없애고 날짜를 클릭 했을 때 작성하는 form이 뜨도록 변경
2. 이미 작성된 투두가 있는 날짜를 클릭했을 때 해당되는 것 조회하도록 수정
등등이 있습니다.

**Comment by Ne-eun** [comment]
1. 저는 주간달력을 생각했는데 월간달력으로 만드신것같습니다.
 - 월간 달력으로 가고 싶으신건지?
2. 제가 생각한 API는 시작날짜/종료날짜를 파라미터로 날리면 해당사이에 있는 투두목록 전체를 내려 줄 생각이었습니다.
 - 전체 목록을 불러와서 클라이언트에서 정렬하고 가공하는걸 생각했는데 원하시는 방향이 있으신가요?
 - 이렇게 기획한 이유는 React-query의 fetch기능과 상태관리를 사용해보기 위함이었습니다. 
3. 컨텐츠 추가방식은 상위주간달력에 선택된 날짜를 기준으로 컨텐츠가 생성되는걸 생각했습니다.
- 상위 달력부분과 컨텐츠를 생성하고 목록을 노출시키는 부분에서 보다 복잡한? 상태관리 라이브러리 사용이 목적입니다.

**Comment by yestw** [comment]
1, 2번 항목들 이해했습니다.
- 월간 달력 -> 주간 달력 변경
- 시작날짜/종료날짜 받을 수 있는 input - date 형식의 화면 만들도록 하겠습니다.

1. 월간달력으로 만든 이유는 우선적으로 캘린더를 구현해보기 위해 인터넷을 찾아보다 발견했던 라이브러리가 있어 구현했던 부분이여서 주간달력으로 바꾸면 될 것 같습니다!
2. 따로 원했던 것은 없었고 어떻게 조회할 지 정하는 부분이 있었으면 되었기에 말씀주신대로 구현해서  React-query를 공부하고 사용해볼 수 있도록 하겠습니다!
--- 
3번 항목은 조금 이해가 안되는데, 혹시 이전에 저에게 보내주셨던 이미지를 생각하면 되는 부분인지 궁금합니다!
- 이전에 보내주셨던 이미지에서 날짜를 클릭하면 여러개의 컨텐츠를 추가할 수 있는 것인지 궁금합니다.

**Comment by Ne-eun** [comment]
1. 상단의 달력은 주간달력으로 한다. (오늘날짜 기준 일~토까지)
2. 상단의 달력에서 선택된 날짜가 투두목록생성 기준날짜가 된다.
3. 멀티생성기능은 우선은 제외되고 추후에 추가 논의 후 개발한다.
4. 시작날짜/종료날짜 (이번주의 시작일, 이번주의 마지막일)의 전체 목록을 서버에서 제공한다.

* 필요 API
시작날짜/종료날짜 안에 포함된 컨텐츠 전체목록 제공
